# Generated by Django 4.1.7 on 2023-04-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='UserModel',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
