# Generated by Django 4.1.7 on 2023-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_testmodel_usermodel_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='name',
            field=models.CharField(help_text='Enter a food truck name (e.g. Don Memos)', max_length=100),
        ),
    ]
