# Generated by Django 4.1.7 on 2023-04-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_foodtruck_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTruck',
            new_name='FoodTruckModel',
        ),
    ]
