# Generated by Django 4.1.7 on 2023-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
