# Generated by Django 4.1.7 on 2023-04-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reviewmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='author',
        ),
    ]
