# Generated by Django 4.1.7 on 2023-04-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_reviewmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='author',
            field=models.CharField(default='Anon', max_length=50),
        ),
    ]
