# Generated by Django 4.2 on 2023-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_reviewmodel_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodtruckmodel",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Enter food truck location",
                max_length=200,
                null=True,
            ),
        ),
    ]
