# Generated by Django 4.2 on 2023-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_foodtruckmodel_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("ingredients", models.ManyToManyField(to="main.ingredients")),
            ],
        ),
        migrations.AddField(
            model_name="foodtruckmodel",
            name="menu_item",
            field=models.ManyToManyField(to="main.menuitem"),
        ),
    ]
