# Generated by Django 4.2 on 2023-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_ingredients_menuitem_foodtruckmodel_menu_item"),
    ]

    operations = [
        migrations.RemoveField(model_name="menuitem", name="ingredients",),
        migrations.RemoveField(model_name="foodtruckmodel", name="menu_item",),
        migrations.DeleteModel(name="Ingredients",),
        migrations.DeleteModel(name="MenuItem",),
        migrations.AddField(
            model_name="foodtruckmodel",
            name="menu_item",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
