# Generated by Django 4.1.7 on 2023-04-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reviewmodel_author'),
        ('main', '0012_leaderboardmodel'),
    ]

    operations = [
    ]
