# Generated by Django 4.1.7 on 2023-04-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_0009_reviewmodel_author_0012_leaderboardmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtruckmodel',
            old_name='menu_item',
            new_name='menu',
        ),
    ]
