# Generated by Django 4.1.7 on 2023-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_menu_item_foodtruckmodel_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruckmodel',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruckmodel',
            name='lon',
            field=models.IntegerField(null=True),
        ),
    ]
