# Generated by Django 4.1.7 on 2023-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_foodtruckmodel_lat_foodtruckmodel_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckmodel',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodtruckmodel',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
